# Generated by Django 4.0.4 on 2022-07-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LineOfEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('percent_complete', models.IntegerField()),
                ('dependencies', models.CharField(max_length=255)),
                ('lineOfEffort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_range_planner.lineofeffort')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='long_range_planner.asset')),
            ],
        ),
    ]
