# Generated by Django 4.0.4 on 2022-07-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('long_range_planner', '0003_remove_task_asset_alter_task_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='long_range_planner.asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.CharField(max_length=255),
        ),
    ]
