# Generated by Django 4.0.4 on 2022-07-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('long_range_planner', '0005_alter_task_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lineOfEffort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='long_range_planner.lineofeffort'),
        ),
    ]
