# Generated by Django 4.0.4 on 2022-07-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('long_range_planner', '0010_alter_task_asset_alter_task_lineofeffort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='long_range_planner.asset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='lineOfEffort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effort', to='long_range_planner.lineofeffort'),
        ),
    ]
