# Generated by Django 4.0.4 on 2022-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_range_planner', '0011_alter_task_asset_alter_task_dependencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
    ]
